### ISSUE TITLE
Add support for parsing comments

### ISSUE THREAD

**Issue by jamescurtin** [joshtemple/lkml#21]
**User story**: As a developer, I want to autoformat LookML (via a round trip through `lkml.load` and `lkml.dump`, for example) in conjunction w/ a style linter.

**Blocker**: `lkml` currently does not store commented out code. The [`lams`](https://github.com/looker-open-source/look-at-me-sideways) linter uses comments to ignore warnings. Therefore, LAMS would fail on the following code if it was formatted w/ `lkml`.

```yaml
view: order {
  sql_table_name: sales.order ;;
  dimension: customer_name {
    label: "Customer Name"
    type: string
    sql: ${customer.name} ;;
    # LAMS
    # rule_exemptions: {
    #  F1: "This is really important to keep for some reason"
    # }
  }
}
```

**Comment by joshtemple** [comment]
This is a good idea! It will require some changes to the lexer so that a `CommentToken` is created instead of skipping over comments during scanning.

As far as parsing goes, I'm imagining a `comment` key/value that's added to the dictionary, similar to `name`, that stores the full, multi-line text of the comment (newlines included). Is that how you were imagining comments parsed?

For serializing, you would need to split the `comment` value on newlines and print them out with the preceding `#`.

**Comment by jamescurtin** [comment]
I think that makes sense, though for comments to be fully supported, the position of the comments would need to be preserved when serialized.

Consider the following example:

```yml
# Name of view maintainer
# Copyright notice

view: view_name {
  # Description of view
  sql_table_name: schema.table_name ;; # Note about the table

  dimension: a_dimension {
    type: string
    sql: ${TABLE}.a_dimension ;;
    # LAMS
    # warning
    # ignore
    # block
  }

  dimension_group: a_dimension_group {
    type: time
    timeframes: [
      raw,
      time,
      # month,
    ]
    sql: ${TABLE}.a_dimension_group ;;
  }
}
```

Thoughts?
