### ISSUE TITLE
Parsing *.dashboard files

### ISSUE THREAD

**Issue by wsjk** [joshtemple/lkml#79]
It doesn't seem like this package supports parsing of LookML dashboard files?

**Comment by joshtemple** [comment]
I haven't explicitly tested it with LookML dashboard files. If you're able to upload a snippet of LookML that reproduces the error, I can try and work out a fix.

**Comment by wsjk** [comment]
Sure here's an example you can get when in an Explore and using `Get LookML` to get the LookML for dashboard tile

```
- name: add_a_unique_name_1683211649
  title: Untitled Visualization
  model: core
  explore: some_explore
  type: looker_grid
  fields: [some_explore.day, some_explore.id]
  filters:
    some_explore.date: 2023/04/30
  sorts: [some_explore.day desc]
  limit: 500
  column_limit: 50
  show_view_names: false
  show_row_numbers: true
  transpose: false
  truncate_text: true
  hide_totals: false
  hide_row_totals: false
  size_to_fit: true
  table_theme: white
  limit_displayed_rows: false
  enable_conditional_formatting: false
  header_text_alignment: left
  header_font_size: 12
  rows_font_size: 12
  conditional_formatting_include_totals: false
  conditional_formatting_include_nulls: false
  defaults_version: 1
```
